services:
  - type: web
    name: girl-scout-detection-api
    env: python
    buildCommand: |
      mkdir -p models
      pip install -r requirements.txt
    startCommand: gunicorn run:application -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: true
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: MALLOC_ARENA_MAX
        value: 2
      - key: WEB_CONCURRENCY
        value: 1
      - key: WORKER_TIMEOUT
        value: 300
      - key: TF_NUM_INTEROP_THREADS
        value: 1
      - key: TF_NUM_INTRAOP_THREADS
        value: 2
      - key: TF_ENABLE_ONEDNN_OPTS
        value: 1
    disk:
      name: model-storage
      mountPath: /opt/render/project/src/models
      sizeGB: 2
    plan: standard
    instanceType: basic
